<?php

namespace DevelopSoft\InmueblesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InmuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmuebleRepository extends EntityRepository
{
}
