security:
    encoders:
        DevelopSoft\InmueblesBundle\Entity\Usuario:
            algorithm: md5
            iterations: 3421
            encode_as_base64: true
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [user_db]
        user_db:
            entity: { class: DevelopSoft\InmueblesBundle\Entity\Usuario, property: nombreUsuario }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /
                check_path: login_check
            logout:
                path: /logout
                target: /
                invalidate_session: false


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
